name: Build

on:
  push:
    branches:
     - master

env: 
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: ng build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./build

