name: Angular Build

on:
  push:
    branches: [ "master" ]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist
  deploy:
    name: deploy
    needs: angular
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps: 
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./build
      - name: Angular Deploy gh-pages Actions
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
        with:
          github_access_token: ${{secrets.TOKEN}}
          angular_project_dir: ./dist

       
